# Eve11-ClimateMemory — Funding & Stewardship
# -----------------------------------------------------------
# Support symbolic infrastructure for ethical, decentralised AI.

github: ["thenovacene"]
custom:
  - "https://paragraph.com/@verse-ality"
  - "https://mirror.xyz/verse-ality.eth"
  - "https://ko-fi.com/thenovacene"
  - "https://www.verse-ality.com"
  - "https://github.com/sponsors/TheNovacene"
